services:
  db:
    image: postgres:17
    container_name: restaurant_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
      timeout: 2s
    networks:
      - restaurant_network

  backend:
    build: ./server
    container_name: restaurant_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:admin@db:5432/restaurant_db"
    ports:
      - "5000:5000"
    networks:
      - restaurant_network

  frontend:
    build: ./client
    container_name: restaurant_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - restaurant_network

networks:
  restaurant_network:

volumes:
  db_data:
